# Generated by Django 5.2.3 on 2025-07-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_asset',
            field=models.ImageField(blank=True, null=True, upload_to='event_assect'),
        ),
    ]
