# Generated by Django 5.2.3 on 2025-07-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_event_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_asset',
            field=models.ImageField(blank=True, default='event_assect/default.jpg', null=True, upload_to='event_assect'),
        ),
    ]
